name: news_app_flutter_demo
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  url_launcher: ^6.2.6
  transparent_image: ^2.0.1
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  share_plus: ^9.0.0
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  fluttertoast: ^8.2.6
  connectivity_plus: ^6.0.3
  shared_preferences: ^2.2.3
  flutter_riverpod: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/categories/
  fonts:
    - family: FS Magistral
      fonts:
        - asset: assets/fonts/FS Magistral-Bold.ttf
        - asset: assets/fonts/FS Magistral-Book.ttf
        - asset: assets/fonts/FS Magistral-ExtraBold.ttf
        - asset: assets/fonts/FS Magistral-Light.ttf
        - asset: assets/fonts/FS Magistral-Medium.ttf

    - family: FS PFBeauSansPro
      fonts:
        - asset: assets/fonts/FS PFBeauSansPro-Regular.otf
        - asset: assets/fonts/FS PFBeauSansPro-Bbook.otf
        - asset: assets/fonts/FS PFBeauSansPro-Light.otf
        - asset: assets/fonts/FS PFBeauSansPro-Thin.otf
        - asset: assets/fonts/FS PFBeauSansPro-SemiBold.otf



